import Head from "next/head";
import React from "react";
import NavBar from "../navigation";

export interface LayoutPropsModel {
  title?: string;
}

const Layout: React.FunctionComponent<
  React.PropsWithChildren<LayoutPropsModel>
> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex flex-col">{children}</main>
    </>
  );
};

const getLayout = (page: React.ReactElement) => {
  return <Layout>{page}</Layout>;
};

export { Layout, getLayout };
